import { Program } from "@/types/Workout";
import { v4 as uuidv4 } from "uuid";

export const templateConfigs: Program[] = [
  {
    id: "template-ppl-3day",
    name: "Push Pull Legs ",
    description: "A balanced 3-day split for building strength and muscle.",
    goal: "hypertrophy",
    mode: "days",
    createdAt: new Date(),
    updatedAt: new Date(),
    days: [
      {
        id: uuidv4(),
        name: "Push",
        description: "Chest, shoulders, triceps.",
        workout: [],
        order: 0,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Pull",
        description: "Back and biceps.",
        workout: [],
        order: 1,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Legs",
        description: "Quads, glutes, hamstrings.",
        workout: [],
        order: 2,
        type: "workout",
      },
    ],
  },
  {
    id: "template-upper-lower-4day",
    name: "Upper Lower",
    description: "Classic upper/lower split with recovery built in.",
    goal: "strength",
    mode: "days",
    createdAt: new Date(),
    updatedAt: new Date(),
    days: [
      {
        id: uuidv4(),
        name: "Upper A",
        description: "Bench, row, overhead press.",
        workout: [],
        order: 0,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Lower A",
        description: "Squat focused day.",
        workout: [],
        order: 1,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Upper B",
        description: "Incline press, lat pulldown.",
        workout: [],
        order: 2,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Lower B",
        description: "Deadlift focused day.",
        workout: [],
        order: 3,
        type: "workout",
      },
    ],
  },
  {
    id: "template-full-body-3day",
    name: "Full Body",
    description: "Beginner-friendly full-body routine done 3x per week.",
    goal: "strength",
    mode: "days",
    createdAt: new Date(),
    updatedAt: new Date(),
    days: [
      {
        id: uuidv4(),
        name: "Day 1",
        description: "Push + legs",
        workout: [],
        order: 0,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Day 2",
        description: "Pull + legs",
        workout: [],
        order: 1,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Day 3",
        description: "Mixed strength and hypertrophy",
        workout: [],
        order: 2,
        type: "workout",
      },
    ],
  },
  {
    id: "template-athlete-performance",
    name: "Athlete Performance",
    description: "Train like an athlete—power, speed, and strength focused.",
    goal: "power",
    mode: "blocks",
    createdAt: new Date(),
    updatedAt: new Date(),
    blocks: [
      {
        id: uuidv4(),
        name: "Performance Block",
        order: 0,
        weeks: 4,
        days: [
          {
            id: uuidv4(),
            name: "Power",
            description: "Olympic lifts, jumps",
            workout: [],
            order: 0,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Strength",
            description: "Squat + push press",
            workout: [],
            order: 1,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Speed/Agility",
            description: "Sprints, lateral drills",
            workout: [],
            order: 2,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Mixed",
            description: "Complexes + sport-specific work",
            workout: [],
            order: 3,
            type: "workout",
          },
        ],
      },
    ],
  },
  {
    id: "template-bodybuilder-5day",
    name: "Bodybuilder Split",
    description: "Classic bro split for maximum hypertrophy.",
    goal: "hypertrophy",
    mode: "days",
    createdAt: new Date(),
    updatedAt: new Date(),
    days: [
      {
        id: uuidv4(),
        name: "Chest",
        description: "Flat, incline, accessories",
        workout: [],
        order: 0,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Back",
        description: "Vertical and horizontal pulls",
        workout: [],
        order: 1,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Legs",
        description: "Quads, hams, calves",
        workout: [],
        order: 2,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Shoulders",
        description: "Delts and traps",
        workout: [],
        order: 3,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Arms",
        description: "Biceps and triceps",
        workout: [],
        order: 4,
        type: "workout",
      },
    ],
  },
  {
    id: "template-powerbuilder-4day",
    name: "Powerbuilder",
    description: "Hybrid program combining strength and hypertrophy.",
    goal: "hypertrophy",
    mode: "blocks",
    createdAt: new Date(),
    updatedAt: new Date(),
    blocks: [
      {
        id: uuidv4(),
        name: "Powerbuilding Phase",
        order: 0,
        weeks: 4,
        days: [
          {
            id: uuidv4(),
            name: "Upper Power",
            description: "Bench + heavy upper",
            workout: [],
            order: 0,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Lower Power",
            description: "Squat/DL focus",
            workout: [],
            order: 1,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Upper Volume",
            description: "Lighter hypertrophy upper",
            workout: [],
            order: 2,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Lower Volume",
            description: "Higher rep lower day",
            workout: [],
            order: 3,
            type: "workout",
          },
        ],
      },
    ],
  },
  {
    id: "template-minimalist-2day",
    name: "Minimalist",
    description: "A time-efficient full-body plan for busy lifters.",
    goal: "strength",
    mode: "days",
    createdAt: new Date(),
    updatedAt: new Date(),
    days: [
      {
        id: uuidv4(),
        name: "Day 1",
        description: "Squat + push + hinge",
        workout: [],
        order: 0,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Day 2",
        description: "Deadlift + pull + core",
        workout: [],
        order: 1,
        type: "workout",
      },
    ],
  },
  {
    id: "template-conditioning-3day",
    name: "Conditioning + Strength",
    description: "Endurance, circuits, and light strength in one program.",
    goal: "endurance",
    mode: "days",
    createdAt: new Date(),
    updatedAt: new Date(),
    days: [
      {
        id: uuidv4(),
        name: "Strength",
        description: "Compound lifts",
        workout: [],
        order: 0,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Conditioning",
        description: "HIIT and sled work",
        workout: [],
        order: 1,
        type: "workout",
      },
      {
        id: uuidv4(),
        name: "Mixed",
        description: "Bodyweight circuits + carries",
        workout: [],
        order: 2,
        type: "workout",
      },
    ],
  },
  {
    id: "template-athlete-blocks",
    name: "Athlete Performance",
    description: "Train like an athlete—power, speed, and strength focused.",
    goal: "power",
    mode: "blocks",
    createdAt: new Date(),
    updatedAt: new Date(),
    blocks: [
      {
        id: uuidv4(),
        name: "Block 1",
        order: 0,
        days: [
          {
            id: uuidv4(),
            name: "Power",
            description: "",
            workout: [],
            order: 0,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Speed",
            description: "",
            workout: [],
            order: 1,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Strength",
            description: "",
            workout: [],
            order: 2,
            type: "workout",
          },
          {
            id: uuidv4(),
            name: "Recovery",
            description: "",
            workout: [],
            order: 3,
            type: "workout",
          },
        ],
      },
    ],
  },
];
